[workspace]
members = ["dec_01"]
resolver = "3"

[workspace.package]
rust-version = "1.91.1"
edition = "2024"

[workspace.dependencies]
anyhow = "1.0.100"

[workspace.lints.clippy]
cast_possible_truncation = "deny"
